# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_mainshow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainshow',
            old_name='brandname',
            new_name='brand_name',
        ),
    ]
