# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20181102_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainshow',
            old_name='rack_id',
            new_name='track_id',
        ),
    ]
