# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20181102_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foodtypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.CharField(max_length=10)),
                ('type_name', models.CharField(max_length=100)),
                ('child_type_names', models.CharField(max_length=100)),
                ('type_sort', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'axf_foodtypes',
            },
        ),
    ]
