# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_foodtypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtypes',
            name='child_type_names',
            field=models.CharField(max_length=256),
        ),
    ]
