# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20181102_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10)),
                ('product_img', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_long_name', models.CharField(max_length=100)),
                ('is_xf', models.BooleanField(default=False)),
                ('pmdesc', models.BooleanField(default=False)),
                ('specifics', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category_id', models.IntegerField()),
                ('child_id', models.IntegerField()),
                ('child_id_name', models.CharField(max_length=100)),
                ('dealer_id', models.CharField(max_length=10)),
                ('store_nums', models.IntegerField()),
                ('product_num', models.IntegerField()),
            ],
            options={
                'db_table': 'axf_goods',
            },
        ),
    ]
